### ISSUE TITLE
The upload doesn't work for me...

### ISSUE THREAD

**Issue by torben-erz** [ClaesClaes/Arduino-ESP32-NimBLE-OTA-iOS-SwiftUI#1]
Hello, I am trying to run your project but unfortunately I am not having success uploading the bin file. A BLE connection can be established with the ESP32-WROOM-32D (ESP32 Dev Module). But when I then try to upload the bin file it only manages to 0.4%. Then the connection is disconnected. I have also tried with different chunks (1-4). Without success. Why does this happen? I ask for your support - Thank you

**Comment by ClaesClaes** [comment]
Hi, a number of issues could be behind what you experience. Could you let me know which version of NimBLE you are running? Secondly assuming you run version 1.3.1 (latest I tested on)  or lower have you set the following in the nimconfig.h file:

// The following file needs to be changed: "nimconfig.h"
// Line 14: uncomment and increase MTU size to: #define CONFIG_BT_NIMBLE_ATT_PREFERRED_MTU 512
// Line 45: uncomment : #define CONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED
// Line 50: uncomment : #define CONFIG_BT_NIMBLE_ROLE_OBSERVER_DISABLED
// Line 86: uncomments and increase stack size to : #define CONFIG_BT_NIMBLE_TASK_STACK_SIZE 8192

**Comment by torben-erz** [comment]
Hello, thank you very much for your quick reply. 

I had used the NimBLE version 1.4.1. Now I switched to version 1.3.1 and made the adjustments in the "nimconfig.h" as you describe. Then I reflashed the ESP32 and tried again. Unfortunately still no success. 

I'm using iOS 15 because I don't have a device with iOS 14 anymore. But I don't think it's because of the iOS version. How can I find out the core version of the ESP32? 

Do you have another idea to work?

**Comment by ClaesClaes** [comment]
Hi, so let's see what we can do. iOS15 should be fine. I wrote the Swift part when using iOS15 and it also worked on iOS16. I do see that there's two BLE object swift files in the repository. Swift should only load BluetoothLE.swift but for whatever reason I also added BLE_Object.swift in the Github repository. I have now deleted that file. So make sure you have the right BLE swift file in the Swift project.

If the above was not the issue I can recommend turning on the 'Core debug level:' (in Arduino) to 'Verbose' so you can see in the serial terminal what is happening when the OTA download fails and go from there.  

You should also check the Partition Scheme in Arduino is set so you can actually do an OTA. See image how I 
had set it up:

![image](https://github.com/ClaesClaes/Arduino-ESP32-NimBLE-OTA-iOS-SwiftUI/assets/10321738/df5188db-a27b-45f6-999c-c7285c74411d)

**Comment by ClaesClaes** [comment]
see issue [#3]([](https://github.com/ClaesClaes/Arduino-ESP32-NimBLE-OTA-iOS-SwiftUI/issues/3)) for a possible solution to your problem.
