### ISSUE TITLE
Invalid magic byte error

### ISSUE THREAD

**Issue by Aizudev** [ClaesClaes/Arduino-ESP32-NimBLE-OTA-iOS-SwiftUI#2]
Thank you for your example!

I uploaded your .ino code onto an ESP32, and your swift code onto xcode, and ran it in a simulator. I managed to get the BLE OTA working pretty smoothly for the past year.

However, 2 days ago, I was suddenly unable to build the xcode app, and so I cleared the build folder and rebuilt it. This time however, it was got stuck at 0.2%. I then update xcode to the latest version 15 (from 14) and also ran the app on my phone instead of the simulator. The error on the ESP32 was:

```
main loop started
1. BeginOTA
2. Running partition type 0 subtype 17 (offset 0x00150000)  
3. Writing to partition subtype 16 at offset 0x10000        
--Data received---
4. Final byte arrived
E (177294) esp_image: invalid segment length 0xffffffff
OTA end failed
1. BeginOTA
2. Running partition type 0 subtype 17 (offset 0x00150000)  
3. Writing to partition subtype 16 at offset 0x10000        
E (179401) esp_ota_ops: OTA image has invalid magic byte (expected 0xE9, saw 0x4d)
Error: write to flash failed
1. BeginOTA
2. Running partition type 0 subtype 17 (offset 0x00150000)  
3. Writing to partition subtype 16 at offset 0x10000        
E (180952) esp_ota_ops: OTA image has invalid magic byte (expected 0xE9, saw 0x25)
Error: write to flash failed
1. BeginOTA
2. Running partition type 0 subtype 17 (offset 0x00150000)  
3. Writing to partition subtype 16 at offset 0x10000        
E (182406) esp_ota_ops: OTA image has invalid magic byte (expected 0xE9, saw 0x20)
Error: write to flash failed
```

When I tried uploading another firmware, it was stuck at 0.7%, with the same magic byte error. The respective firmware were consistently stuck at 0.2 and 0.7%.

I then tried the upload the same binaries via webserver HTTP OTA, where the ESP runs a server and we send the firmware binary directly to it's server endpoint, over a local network. This worked for both binaries. 

I tried the .ino code with the update nimble library configs as you suggested with nimble version 1.3, and also tried without updating the library configs with version 1.4, but got the same error.

Would you know what the issue might be or how we might be able to debug it?

**Comment by ClaesClaes** [comment]
Hi, it was a while ago I wrote this. From the error description it looks like the ESP32 is not able to keep up writing to the flash memory. However to rule out any iOS or Xcode version issues ut I can try to replicate your error and see what can be the issue. It might take a few day though before I can do it.

**Comment by Aizudev** [comment]
Thank you! I made some progress.

Turns out iOS app was sending chunks of 509 length, and not 511. It was breaking [this](https://github.com/ClaesClaes/Arduino-ESP32-NimBLE-OTA-iOS-SwiftUI/blob/main/esp32_NimBLE_ota/esp32_NIMBLE_ota.ino#L152) condition and so it messed up the flow. I changed it to 509 and it updated successfully.

I'm not sure why the chunk size would suddenly change though. That is something I'm still looking into.

**Comment by ClaesClaes** [comment]
Hi, good that you found the issue. Yes 3 bytes of an header are added per the BLE specification so when you send a chunk of x bytes it retracts 3 bytes to make room for the header. And then look for the same size chunk -3 bytes in the .ino file.

You see this from line 435 in BluetoothLE.swift:
chunkSize = discoveredPeripheral.maximumWriteValueLength (for: .withoutResponse) - 3

the ESP .ino file assumes that the final chunk is less than 510 bytes as seen in line 152:
if (rxData.length() < 510) // TODO Asumes at least 511 data bytes (@BLE 4.2).

This is hard coded but can of course be handled better by checking the length of the first package and set the length in a variable instead of hard coding it.
